# Generated by Django 4.2.11 on 2024-03-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='Meal_type',
            new_name='Meal',
        ),
    ]
